CREATE TABLE holidays ( id INTEGER PRIMARY KEY, name VARCHAR(50), country VARCHAR(30), date_of_event VARCHAR(10) );

INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Republic Day', '2009-01-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Maha Shivratri', '2009-02-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Holi', '2009-03-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Mahavir Jayanthi', '2009-04-07');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Good Friday', '2009-04-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'May Day', '2009-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Buddha Purnima', '2009-05-08');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Krishna Janmastami', '2009-08-14');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Independence Day', '2009-08-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Ganesh Chaturthi', '2009-08-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Id-Ul-Fitr', '2009-09-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Vijaya Dashami', '2009-09-28');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Mahatma Gandhi Jayanti', '2009-10-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Diwali', '2009-10-17');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Guru Nanak Jayanthi', '2009-11-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Christmas', '2009-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Martin Luther King Day', '2009-01-19');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Washingtons Birthday', '2009-02-16');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Memorial Day', '2009-05-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Independence Day', '2009-07-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Labor Day', '2009-09-07');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Columbus Day', '2009-10-12');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Veterans Day', '2009-11-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Thanksgiving Day', '2009-11-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Christmas Day', '2009-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Good Friday', '2009-04-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Early May', '2009-05-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Spring Bank Holiday', '2009-05-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Summer Bank Holiday', '2009-08-31');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Christmas Day', '2009-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Boxing Day', '2009-12-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Bank Holiday', '2009-12-28');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Coming of age day', '2009-01-12');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'National Foundation day', '2009-02-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Vernal Equiniox day', '2009-03-20');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Showa day', '2009-04-29');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Constitution Memorial Day', '2009-05-03');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Greenery day', '2009-05-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Childrens Day', '2009-05-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Marine Day', '2009-07-20');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Respect for the aged Day', '2009-09-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Bridge Public Holiday', '2009-09-22');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Autumnal Equiniox day', '2009-09-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Health and Sports Day', '2009-10-12');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Culture Day', '2009-11-03');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Labour Thanksgiving Day', '2009-11-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'The Emperors Birthday', '2009-12-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Chinese Lunar New Year', '2009-01-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Chinese Lunar New Year', '2009-01-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Chinese Lunar New Year', '2009-01-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Qing Ming Festival', '2009-04-06');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Labor Day', '2009-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Dragon Boat Festival', '2009-05-28');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'National Day', '2009-10-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'National Day', '2009-10-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'National Day', '2009-10-03');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Mid-Autumn Festival', '2009-10-03');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Chinese New Year', '2009-01-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Chinese New Year', '2009-01-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Good Friday', '2009-04-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Labour Day', '2009-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Vesak Day', '2009-05-09');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'National Day', '2009-08-09');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Hari Raya Puasa', '2009-09-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Deepavali', '2009-11-17');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Hari Raya Haji', '2009-11-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Christmas', '2009-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Human Rights Day', '2009-03-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Good Friday', '2009-04-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Family Day', '2009-04-13');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Freedom Day', '2009-04-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Workers Day', '2009-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Youth Day', '2009-06-16');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'National Womens Day', '2009-08-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Heritage Day', '2009-09-24');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Day of Reconciliation', '2009-12-16');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Christmas Day', '2009-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Day of Goodwill', '2009-12-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Epiphany', '2009-01-06');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Easter', '2009-04-12');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Easter Monday', '2009-04-13');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Anniversary of Liberation', '2009-04-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Labour Day', '2009-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Republic Day', '2009-06-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Assumption Day', '2009-08-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'All Saints', '2009-11-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Immaculate Conception', '2009-12-08');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Christmas Day', '2009-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'St Stephens Day', '2009-12-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'New Years Day', '2009-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Easter', '2009-04-12');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Easter Monday', '2009-04-13');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'V-E Day', '2009-04-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Labour Day', '2009-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Ascension Day', '2009-05-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Pentecost', '2009-05-31');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Whit Monday', '2009-06-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Bastille Day', '2009-07-14');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Assumption of Mary', '2009-08-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'All Saints Day', '2009-11-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Armistice Day', '2009-11-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Christmas Day', '2009-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Republic Day', '2010-01-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Maha Shivratri', '2010-02-12');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Holi', '2010-02-28');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Mahavir Jayanthi', '2010-03-28');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Good Friday', '2010-04-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'May Day', '2010-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Buddha Purnima', '2010-05-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Krishna Janmastami', '2010-09-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Independence Day', '2010-08-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Ganesh Chaturthi', '2010-09-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Id-Ul-Fitr', '2010-09-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Vijaya Dashami', '2010-10-17');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Mahatma Gandhi Jayanti', '2010-10-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Diwali', '2010-11-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Guru Nanak Jayanthi', '2010-11-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('India', 'Christmas', '2010-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Martin Luther King Day', '2010-01-18');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Washingtons Birthday', '2010-02-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Memorial Day', '2010-05-31');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Independence Day', '2010-07-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Labor Day', '2010-09-06');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Columbus Day', '2010-10-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Veterans Day', '2010-11-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Thanksgiving Day', '2010-11-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Christmas Day', '2010-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Good Friday', '2010-04-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Early May', '2010-05-03');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Spring Bank Holiday', '2010-05-31');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Summer Bank Holiday', '2010-08-30');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Christmas Day', '2010-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Boxing Day', '2010-12-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('UK', 'Bank Holiday', '2010-12-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Coming of age day', '2010-01-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'National Foundation day', '2010-02-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Vernal Equiniox day', '2010-03-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Showa day', '2010-04-29');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Constitution Memorial Day', '2010-05-03');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Greenery day', '2010-05-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Childrens Day', '2010-05-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Marine Day', '2010-07-19');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Respect for the aged Day', '2010-09-20');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Bridge Public Holiday', '2010-09-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Autumnal Equiniox day', '2010-09-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Health and Sports Day', '2010-10-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Culture Day', '2010-11-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'Labour Thanksgiving Day', '2010-11-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Japan', 'The Emperors Birthday', '2010-12-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Chinese Lunar New Year', '2010-02-13');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Chinese Lunar New Year', '2010-02-14');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Chinese Lunar New Year', '2010-02-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Qing Ming Festival', '2010-04-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Labor Day', '2010-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Dragon Boat Festival', '2010-06-16');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'National Day', '2010-10-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'National Day', '2010-10-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'National Day', '2010-10-03');
INSERT INTO holidays (country, name, date_of_event) VALUES ('China', 'Mid-Autumn Festival', '2010-09-22');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Chinese New Year', '2010-02-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Chinese New Year', '2010-02-16');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Good Friday', '2010-04-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Labour Day', '2010-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Vesak Day', '2010-05-28');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'National Day', '2010-08-09');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Hari Raya Puasa', '2010-09-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Deepavali', '2010-11-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Hari Raya Haji', '2010-11-17');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Singapore', 'Christmas', '2010-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Human Rights Day', '2010-03-22');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Good Friday', '2010-04-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Family Day', '2010-04-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Freedom Day', '2010-04-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Workers Day', '2010-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Youth Day', '2010-06-16');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'National Womens Day', '2010-08-09');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Heritage Day', '2010-09-24');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Day of Reconciliation', '2010-12-16');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Christmas Day', '2010-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('South Africa', 'Day of Goodwill', '2010-12-27');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Epiphany', '2010-01-06');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Easter', '2010-04-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Easter Monday', '2010-04-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Anniversary of Liberation', '2010-04-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Labour Day', '2010-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Republic Day', '2010-06-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Assumption Day', '2010-08-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'All Saints', '2010-11-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Immaculate Conception', '2010-12-08');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'Christmas Day', '2010-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('Italy', 'St Stephens Day', '2010-12-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'New Years Day', '2010-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Easter', '2010-04-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Easter Monday', '2010-04-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'V-E Day', '2010-04-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Labour Day', '2010-05-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Ascension Day', '2010-05-13');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Pentecost', '2010-05-23');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Whit Monday', '2010-05-24');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Bastille Day', '2010-07-14');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Assumption of Mary', '2010-08-15');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'All Saints Day', '2010-11-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Armistice Day', '2010-11-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('France', 'Christmas Day', '2010-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'New Year Day', '2011-01-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Martin Luther King Jr. Day', '2011-01-17');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Groundhog Day', '2011-02-02');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Super Bowl Sunday', '2011-02-06');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Valentines Day', '2011-02-14');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Washingtons Birthday', '2011-02-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Ash Wednesday', '2011-03-09');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'St. Patrick Day', '2011-03-17');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'April Fools Day', '2011-04-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Good Friday', '2011-04-22');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Earth Day', '2011-04-22');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Easter', '2011-04-24');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Arbor Day', '2011-04-29');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Cinco de Mayo', '2011-05-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Mothers Day', '2011-05-08');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Memorial Day', '2011-05-30');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Flag Day', '2011-06-14');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Fathers Day', '2011-06-19');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'US Independence Day', '2011-07-04');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Womens Equality Day', '2011-08-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Workers or Labour Day', '2011-09-05');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Patriot Day', '2011-09-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Constitution Day', '2011-09-17');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Rosh Hashanah or Jewish New Year', '2011-09-28');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Yom Kippur or Day of Atonement', '2011-10-07');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Leif Erikson Day', '2011-10-09');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Columbus Day', '2011-10-10');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Halloween', '2011-10-31');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Election Day', '2011-11-01');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Veterans Day', '2011-11-11');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Thanksgiving Day', '2011-11-24');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Pearl Harbor Remembrance Day', '2011-12-07');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Hanukkah', '2011-12-20');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Winter solstice', '2011-12-21');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Christmas Eve', '2011-12-24');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Christmas Day', '2011-12-25');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'Kwanzaa', '2011-12-26');
INSERT INTO holidays (country, name, date_of_event) VALUES ('USA', 'New Year Eve', '2011-12-31');
